Hard coded laser profiles
mrbeam/MrBeamPlugin pull request #1077
Opened 2020-11-17 16:44 UTC by amrsoll

I just cannot understand why i am unable to laser any design, it doesn't make sense.

The 2U and 2C profiles are fine, and the `Profile` I deleted was not used. Re-instating it didn't help either.

2020-11-23 16:04 UTC, amrsoll commented on octoprint_mrbeam/printing/profile.py
> +        #     )
@Gallore I believe this is part of the deprecated feature where you could modify the profile from the front end?

2021-01-05 11:50 UTC, amrsoll commented on octoprint_mrbeam/printing/profile.py
> +        pass
OP related : migration script related - not used in our codebase

2021-01-05 11:53 UTC, amrsoll commented on octoprint_mrbeam/printing/profile.py
> +
Check : Are we still relying on the lasercutterSettings ?

2021-01-05 11:57 UTC, amrsoll commented on octoprint_mrbeam/printing/profile.py
> +        return PrinterProfileManager.get_current_or_default(self)
Delete because not logging

2021-01-05 12:01 UTC, Gallore requested changes

2021-01-05 12:01 UTC, andywerner commented on octoprint_mrbeam/printing/profiles/mrb1.py
> +)
remove Mr Beam 1 profiles. no need to support mrb1

2021-01-05 12:01 UTC, andywerner commented on octoprint_mrbeam/printing/profiles/dummy.py
> +    start_method="onebutton",  # change ?
start_method can be removed

2021-01-05 12:01 UTC, andywerner commented on octoprint_mrbeam/__init__.py
>      @octoprint.plugin.BlueprintPlugin.route("/profiles", methods=["GET"])
please remove all everything that was meant to change profile from frontend. There's also a jinja file....

2021-01-05 12:01 UTC, andywerner commented on octoprint_mrbeam/printing/profile.py
> +        # TODO
remove TODO comment

2021-01-05 12:01 UTC, andywerner commented on octoprint_mrbeam/printing/profile.py
> +        #     )
please remove all code related to the feature to change profile from the frontend.

2021-01-05 12:01 UTC, Gallore commented on octoprint_mrbeam/templates/settings/lasercutterprofiles_settings.jinja2
> +			<a href="#" class="icon-pencil" title="Edit Profile" data-bind="click: function() { if(!$root.isReadOnly($data)) $root.showEditProfileDialog($data); }"></a>&nbsp;|&nbsp;<a href="#" class="icon-tra
please remove this file

2021-01-25 21:52 UTC, amrsoll commented on octoprint_mrbeam/printing/profile.py
> +        pass
but necessary

2021-01-26 10:20 UTC, Gallore approved these changes
We already talked about this one before. Not re-reading

2021-01-26 10:28 UTC, merged