Addition of user details to review form
mrbeam/MrBeamPlugin pull request #1151
Opened 2021-02-10 13:19 UTC by khaledsherkawi

2021-02-10 18:35 UTC, Gallore requested changes
Please change as we discussed today on the phone.
In the issue I wrote the wording : https://github.com/mrbeam/MrBeamPlugin/issues/1137#issuecomment-776919717

2021-02-12 10:10 UTC, khaledsherkawi commented
The only thing I kept from before is the back button between screens 1 and 2. The rating bar doesn't look good on top of screen 2. In addition the CSS of the rating bar (on top of screen 2) will be confusing to the user. If we leave it without the their decision highlighted they will think that they have to vote again and if we highlight their decision they will think they cannot change it. With the back button they can choose to go back and answer differently. 

Screen 1:
![Screen 1](https://user-images.githubusercontent.com/54568489/107755226-d2ed1300-6d22-11eb-97f3-ef53123551d7.PNG)

Screen 2:
![Screen 2](https://user-images.githubusercontent.com/54568489/107755238-d6809a00-6d22-11eb-8ea8-cddde69bcad7.PNG)

Screen 3 - positive review:
![Screen 3 - Positive Review](https://user-images.githubusercontent.com/54568489/107755258-dc767b00-6d22-11eb-856d-f196cbb28ec2.PNG)

Screen 3 - negative review:
![Screen 3 - Negative Review](https://user-images.githubusercontent.com/54568489/107755247-d8e2f400-6d22-11eb-98c0-a67b66cfe125.PNG)

2021-02-12 10:44 UTC, Gallore requested changes
Here is a description on how to mark text in jinja files: https://sites.google.com/mr-beam.org/wiki/development/internationalization?authuser=0#h.p_lMBteIJOQst1

2021-02-12 10:44 UTC, Gallore commented on octoprint_mrbeam/templates/review.jinja2
> +                    <span class="rating-label">Not at all likely</span>
pls mark for translation

2021-02-12 10:44 UTC, Gallore commented on octoprint_mrbeam/templates/review.jinja2
> +                    <span class="rating-label">Extremely likely</span>
pls mark for translation

2021-02-12 10:44 UTC, Gallore commented on octoprint_mrbeam/templates/review.jinja2
> +                <p>{{ _('Could you take 60 seconds to go to the ') }}
Please bring this whole sentence in one translatable entity with placeholders for opening and closing tag. This is This is important for translations.

2021-02-12 10:44 UTC, Gallore commented on octoprint_mrbeam/templates/review.jinja2
> +                    <a id="give_review_link" target="_blank" href="https://store.mr-beam.org/products/mr-beam-ii-dreamcut-air-filter-ii-bundle?utm_source=beamos&utm_medium=beamos&utm_campaign=review_
please use this URL: `https://mr-beam.org/beamos/review`

2021-02-12 12:13 UTC, Gallore approved these changes

2021-02-12 12:14 UTC, merged