F packaging beamos
mrbeam/MrBeamPlugin pull request #1218
Opened 2021-03-26 13:33 UTC by amrsoll

2021-03-26 14:12 UTC, amrsoll commented on octoprint_mrbeam/os_health_care.py
> +    # FIXME : This should be part of the migration scripts
Could be  migrated to netconnectd

2021-03-26 14:12 UTC, amrsoll commented on octoprint_mrbeam/os_health_care.py
> +    # FIXME : This should be part of the migration scripts
i.e. if it fails to read the network file, assume a default version

2021-03-26 14:12 UTC, amrsoll commented on setup.py
> +plugin_requires = ["webcolors", "pillow", "lxml", "numpy", "picamera"]
Find a way to use pip 9 and update with wheels

2021-04-08 17:11 UTC, Gallore requested changes

2021-04-08 17:11 UTC, andywerner commented on octoprint_mrbeam/util/device_info.py
> -    KEY_IMAGE_CORRECTION_MARKERS = "image_correction_markers"
please keep this

2021-04-08 17:11 UTC, andywerner commented on octoprint_mrbeam/__init__.py
> +        if False:
please change this.

2021-04-08 17:11 UTC, andywerner commented on octoprint_mrbeam/__init__.py
> +                        "sudo /usr/bin/beamos_hostname {}".format(
Please check if `/usr/bin/beamos_hostname` exists and provide a fallback if not

2021-04-08 17:11 UTC, Gallore commented on octoprint_mrbeam/iobeam/iobeam_handler.py
> +    SOCKET_FILE = "/tmp/mrbeam_iobeam.sock"
make this backwards compatible

2021-04-08 17:11 UTC, Gallore commented on octoprint_mrbeam/migrate.py
> +    def track_devpi(self):
- needs to be called
- add try/catch
- add log output indication that this is about to happen

2021-04-12 11:01 UTC, amrsoll commented
Current status: Parking this branch as we are waiting for an other beta release.

2021-05-26 13:15 UTC, amrsoll commented
Cosing in favor of #1265

2021-05-26 13:15 UTC, closed without merging