Add new iobeam logrotate file and refactor migrate.py.
mrbeam/MrBeamPlugin pull request #1221
Opened 2021-03-29 10:44 UTC by amrsoll

This adds a new logrotate file that tracks the `.octoprint/log/iobeam.log`, but does not remove the previous one, so iobeam can log in both locations.

Also the refactoring of `migrate.py` improves readability and makes it more compact, especially if black becomes more leniant (need to change black version in pre-commit)

2021-04-08 16:39 UTC, Gallore requested changes

2021-04-08 16:39 UTC, Gallore commented on octoprint_mrbeam/files/migrate/iobeam_local.logrotate
> +/home/pi/.octoprint/logs/iobeam.log {
please use same logic:
```
/var/log/iobeam.log {
    size 2M
    rotate 4
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
}

```

2021-04-08 16:39 UTC, Gallore commented on octoprint_mrbeam/iobeam/iobeam_handler.py
> +    SOCKET_FILE = "/tmp/mrbeam_iobeam.sock"
make this backwards compatible!!!

2021-05-04 11:44 UTC, amrsoll commented
Closed because of security considerations. It might not be in our best interest to downgrade the privileges of iobeam.

We could reopen again at a later date.

2021-05-04 11:44 UTC, closed without merging