SW-1115 add feature id column to analytics in mr beam
mrbeam/MrBeamPlugin pull request #1502
Opened 2022-05-29 15:20 UTC by ahmed-mrbeam

Please refer to the commit messages for more information

2022-05-29 15:22 UTC, ahmed-mrbeam commented
Next to be Done:
* Test how the feature ID would be used in the code and when 
* Validate that it is written to the analytics json

2022-07-21 13:19 UTC, khaledsherkawi requested changes

2022-07-21 13:19 UTC, khaledsherkawi commented on octoprint_mrbeam/static/js/analytics.js
> +        self.send_frontend_event = function (event, payload, ) {
- `self.send_fontend_event` is rightly corrected to be `self.send_frontend_event` but it is not corrected in the rest of the JS files where this method is used
- What about the last comma in the parameters list? is this a mistake? 
- This method should be fixed to include the feature ID in the parameters. Or should it be in the payload? Please clarify in a comment

2022-07-21 13:19 UTC, khaledsherkawi commented on octoprint_mrbeam/analytics/analytics_handler.py
> +    def add_frontend_event(self, event, payload=None, header_extension=None):
The new method parameter has not been added in `__init__.py` so that frontend analytics could use the feature ID

2022-07-21 13:19 UTC, khaledsherkawi commented on octoprint_mrbeam/analytics/analytics_handler.py
> +                "Exception during add_frontend_event: {}".format(e), analytics=True, header_extension=header_extension
Why is the `header_extension` added as a parameter to the logger exception? Is is not defined as a parameter in `mrb_logger.py`

2022-07-21 13:19 UTC, khaledsherkawi commented on octoprint_mrbeam/analytics/analytics_handler.py
>              self._logger.exception("Exception during add_laserhead_info")
```suggestion
        except Exception as e:
            self._logger.exception("Exception during add_laserhead_info: {}".format(e))
```

2022-07-21 13:19 UTC, khaledsherkawi commented on octoprint_mrbeam/analytics/analytics_handler.py
> +                AnalyticsKeys.Header.FEATURE_ID: header_extension.get(AnalyticsKeys.Header.FEATURE_ID)
```suggestion
                AnalyticsKeys.Header.FEATURE_ID: header_extension.get(AnalyticsKeys.Header.FEATURE_ID, None)
```
I believe it is more readable this way. What do you think?

2022-07-22 08:29 UTC, khaledsherkawi approved these changes

2022-07-22 08:41 UTC, merged