SW-2105 Pre-commit hook to format docstring
mrbeam/MrBeamPlugin pull request #1592
Opened 2022-11-14 10:57 UTC by irlaec

2022-11-15 09:33 UTC, Josef-MrBeam requested changes

2022-11-15 09:33 UTC, Josef-MrBeam commented on octoprint_mrbeam/printing/acc_watch_dog.py
> +        pi-power-and-thermal-issues.html 0b1010000000000000000
This destroys the format of the comment

2022-11-15 09:33 UTC, Josef-MrBeam commented on octoprint_mrbeam/analytics/cpu.py
>            |||             |_ arm frequency capped
here the same

2022-11-15 09:33 UTC, Josef-MrBeam commented on octoprint_mrbeam/analytics/cpu.py
>            |||             ||_ currently throttled
```suggestion
        """See this
        https://harlemsquirrel.github.io/shell/2019/01/05/monitoring-raspberry-
       pi-power-and-thermal-issues.html
        0b1010000000000000000
          1110000000000000010
          |||             |||_ under-voltage
          |||             ||_ currently throttled
```

2022-11-16 08:49 UTC, irlaec commented on octoprint_mrbeam/printing/acc_watch_dog.py
> +        pi-power-and-thermal-issues.html 0b1010000000000000000
Fixed

2022-11-16 08:50 UTC, irlaec commented on octoprint_mrbeam/analytics/cpu.py
>            |||             |_ arm frequency capped
Fixed

2022-11-17 13:46 UTC, Josef-MrBeam approved these changes

2022-11-18 10:12 UTC, merged