SW-2300 detect air filter iii in mr beam plugin
mrbeam/MrBeamPlugin pull request #1651
Opened 2023-01-17 16:43 UTC by Josef-MrBeam

- detect air filter in Mr Beam Plugin
- switch profile of the air filter
- use profiles for maintenance parameters
- use profiles for maintenance page
- fix shopify links

2023-01-18 08:42 UTC, irlaec requested changes

2023-01-18 08:42 UTC, irlaec commented on octoprint_mrbeam/profiles/airfilter_system/airfilter_system_id_8.yaml
> +  - lifespan: 80 #TODO
Could you please add a explanation to these TODO and maybe a ticket number?

2023-01-18 08:42 UTC, irlaec commented on octoprint_mrbeam/static/js/app/view-models/settings/maintenance.js
> +            if (link != null) {
Wouldn't be enough by just returning link? We already assign it a null value if it doesn't have one.
I think we could just remove this second if-else

2023-01-18 08:42 UTC, irlaec commented on tests/iobeam/test_aifilter.py
> +pluginmock = MagicMock(
We have a fixture for the MrBeamPlugin (in conftest), I don't know if it would make sense to use that instead

2023-01-19 08:26 UTC, Josef-MrBeam commented on octoprint_mrbeam/static/js/app/view-models/settings/maintenance.js
> +            if (link != null) {
You are right

2023-01-19 08:27 UTC, Josef-MrBeam commented on octoprint_mrbeam/profiles/airfilter_system/airfilter_system_id_8.yaml
> +  - lifespan: 80 #TODO
sure

2023-01-19 09:12 UTC, Josef-MrBeam commented on tests/iobeam/test_aifilter.py
> +pluginmock = MagicMock(
I changed it to use this instead, thanks for the tip

2023-01-19 09:21 UTC, irlaec approved these changes
I just noticed the name of the test file has a typo --> test_aiRfilter.py

2023-01-19 10:12 UTC, merged