SW-3882 implement the usage percentage for the new filters
mrbeam/MrBeamPlugin pull request #1819
Opened 2023-10-05 13:35 UTC by Josef-MrBeam

2023-10-06 18:35 UTC, irlaec requested changes

2023-10-06 18:35 UTC, irlaec commented on octoprint_mrbeam/analytics/usage_handler.py
> +                carbon_filter=self._get_carbon_filter_usage_time,
I think parenthesis are missing
```suggestion
                carbon_filter=self._get_carbon_filter_usage_time(),
```

2023-10-06 18:35 UTC, irlaec commented on octoprint_mrbeam/analytics/usage_handler.py
> +        usage_time = stage_usage_time if stage_usage_time is not None else 0
Another option (just a suggestion)
```suggestion
        usage_time = stage_usage_time or 0
```

2023-10-06 18:35 UTC, irlaec commented on octoprint_mrbeam/analytics/usage_handler.py
> +        total_percentage = (
Can we just remove the parenthesis?

2023-10-06 18:35 UTC, irlaec commented on octoprint_mrbeam/analytics/usage_handler.py
> +        usage_time = stage_usage_time if stage_usage_time is not None else 0
Same suggestion
```suggestion
        usage_time = stage_usage_time or 0
```

2023-10-06 18:35 UTC, irlaec commented on octoprint_mrbeam/analytics/usage_handler.py
> +            mrb_logger("octoprint.plugins.mrbeam.iobeam.dustmanager").error(
```suggestion
            self._logger.error(
```

2023-10-06 18:35 UTC, irlaec commented on octoprint_mrbeam/analytics/usage_handler.py
> +            mrb_logger("octoprint.plugins.mrbeam.iobeam.dustmanager").error(
```suggestion
            self._logger.error(
```

2023-10-06 18:35 UTC, irlaec commented on octoprint_mrbeam/analytics/usage_handler.py
> +            float: percentage of lifespan that has been used
is it a float? Because for example if usage_time is 0 it would be an int, no?

2023-10-06 18:35 UTC, irlaec commented on octoprint_mrbeam/analytics/usage_handler.py
> +    def _assign_value_and_create_structure(self, nested_keys, value):
Could you please add docstrings for this?
Also, is there a reason to use current_dict instead of self._usage_data?
And last, in `current_dict[nested_keys[-1]]`, is nested_keys[-1]] always supposed to be self.FAN_TEST_RPM_KEY? 

Sorry for all the questions :sweat_smile:

2023-10-06 18:35 UTC, irlaec commented on octoprint_mrbeam/iobeam/airfilter.py
> +        if (
Just a suggestion if you want to try it:
`if all(p is not None for p in [pressure1, pressure2, pressure3, pressure4]):`
or even 
`if all([pressure1, pressure2, pressure3, pressure4]):`
if we want to discard other falsy values as "" or False

2023-10-06 18:35 UTC, irlaec commented on octoprint_mrbeam/iobeam/dust_manager.py
>      def _check_and_report_error(self):
Please add docstrings

2023-10-09 07:28 UTC, Josef-MrBeam commented on octoprint_mrbeam/analytics/usage_handler.py
> +            mrb_logger("octoprint.plugins.mrbeam.iobeam.dustmanager").error(
doesn't work as this is a static method

2023-10-09 07:28 UTC, Josef-MrBeam commented on octoprint_mrbeam/analytics/usage_handler.py
> +            mrb_logger("octoprint.plugins.mrbeam.iobeam.dustmanager").error(
samer here

2023-10-09 07:31 UTC, Josef-MrBeam commented on octoprint_mrbeam/analytics/usage_handler.py
> +    def _assign_value_and_create_structure(self, nested_keys, value):
Ok will add
no, no perticular reasos
no it is the last element of the nested keys can be anything

2023-10-09 07:34 UTC, Josef-MrBeam commented on octoprint_mrbeam/iobeam/dust_manager.py
>      def _check_and_report_error(self):
done

2023-10-09 07:39 UTC, Josef-MrBeam commented on octoprint_mrbeam/analytics/usage_handler.py
> +            float: percentage of lifespan that has been used
good catch, I fixed it

2023-10-10 07:02 UTC, irlaec requested changes

2023-10-10 07:02 UTC, irlaec commented on octoprint_mrbeam/analytics/usage_handler.py
> +            mrb_logger("octoprint.plugins.mrbeam.iobeam.dustmanager").error(
Do we want to keep it static, or was it just because before we weren't using anything from the class?

2023-10-10 07:02 UTC, irlaec commented on octoprint_mrbeam/analytics/usage_handler.py
> +    def _assign_value_and_create_structure(self, nested_keys, value):
So if I understand correctly the "value" is only assigned to the last nested_key, right? If that's the case, could you please clarify this in the docstring or in the name of the method?

2023-10-10 07:02 UTC, irlaec commented on octoprint_mrbeam/analytics/usage_handler.py
>          for key in nested_keys[:-1]:
And is there a reason to loop in the opposite direction? Or couple it be simply
`for key in nested_keys`

2023-10-10 07:02 UTC, irlaec commented on octoprint_mrbeam/analytics/usage_handler.py
> +        total_percentage = (
This is missing :) 
But actually we could also just return time_percentage directly, as you wish

2023-10-10 08:06 UTC, Josef-MrBeam commented on octoprint_mrbeam/analytics/usage_handler.py
> +            mrb_logger("octoprint.plugins.mrbeam.iobeam.dustmanager").error(
The only thing we would use is the logging, but to make it easier I can move it to non static back

2023-10-10 08:06 UTC, Josef-MrBeam commented on octoprint_mrbeam/analytics/usage_handler.py
> +    def _assign_value_and_create_structure(self, nested_keys, value):
Yes that is correct, it will create the nested dict and assign the value to the last key

2023-10-10 08:07 UTC, Josef-MrBeam commented on octoprint_mrbeam/analytics/usage_handler.py
>          for key in nested_keys[:-1]:
it is not the opposit direction, it will exclude the last element

2023-10-10 08:25 UTC, irlaec commented on octoprint_mrbeam/analytics/usage_handler.py
>          for key in nested_keys[:-1]:
Aaaah you're right, sorry I misunderstood :sweat_smile:

2023-10-10 09:24 UTC, Josef-MrBeam commented on octoprint_mrbeam/analytics/usage_handler.py
> +        total_percentage = (
I changed it but it is autoformated like this.
The idea was here to mention that is currently only the time but we can add more

2023-10-10 09:50 UTC, irlaec approved these changes

2023-10-10 10:43 UTC, merged