SW-4141 component improvements
mrbeam/MrBeamPlugin pull request #1838
Opened 2023-11-23 16:06 UTC by Josef-MrBeam

- imporve usage of AF3
- add logging for resetting usage data
- add glitter felt
- fix 1006 malfunction not showing

2023-11-23 16:10 UTC, khaledsherkawi requested changes

2023-11-23 16:10 UTC, khaledsherkawi commented on octoprint_mrbeam/analytics/usage_handler.py
> +        self._logger.info("Reset prefilter usage data")
Please add the percentage value to all the logs

2023-12-06 07:53 UTC, Josef-MrBeam commented on octoprint_mrbeam/analytics/usage_handler.py
> +        self._logger.info("Reset prefilter usage data")
done

2023-12-06 10:01 UTC, khaledsherkawi requested changes

2023-12-06 10:01 UTC, khaledsherkawi commented on octoprint_mrbeam/analytics/usage_handler.py
> +            else 0.1,
This is not very readable. Maybe define it in a variable beforehand and explain in a comment why 0.1

2023-12-06 10:17 UTC, Josef-MrBeam commented on octoprint_mrbeam/analytics/usage_handler.py
> +            else 0.1,
done

2023-12-06 10:50 UTC, khaledsherkawi approved these changes

2023-12-06 10:51 UTC, merged