Laserhead focus reminder
mrbeam/MrBeamPlugin pull request #431
Opened 2019-03-22 13:04 UTC by irlaec

2019-03-22 15:54 UTC, andywerner requested changes

2019-03-22 15:54 UTC, Gallore commented on octoprint_mrbeam/static/css/mrbeam.css
> +  width: 70%;
pls use the new png image

2019-03-22 15:54 UTC, Gallore commented on octoprint_mrbeam/templates/conversion_dialog.jinja2
> +                    <img id="laserhead_focus_reminder_image" src="/plugin/mrbeam/static/img/focus_reminder.jpg">
png

2019-03-22 16:13 UTC, merged

2019-03-25 15:42 UTC, irlaec commented
![](https://github.trello.services/images/mini-trello-icon.png) [(1 + 4) Focus reminder](https://trello.com/c/xS1l4Emw/30-1-4-focus-reminder)