Add laser power correction
mrbeam/MrBeamPlugin pull request #447
Opened 2019-04-08 14:21 UTC by irlaec

2019-04-08 15:13 UTC, irlaec commented
![](https://github.trello.services/images/mini-trello-icon.png) [(4) Laser Power Correction](https://trello.com/c/jZcBPxLh/46-4-laser-power-correction)

2019-04-12 16:03 UTC, andywerner requested changes

2019-04-12 16:03 UTC, andywerner commented on octoprint_mrbeam/__init__.py
> +		self.lh['serial'] = self._settings.get(["laserhead", "serial"])
could you put this into a separate function that return the lh dict to have less clutter here in the initialize method. thx

2019-04-12 16:03 UTC, andywerner commented on octoprint_mrbeam/analytics/analytics_handler.py
> +		self._deviceinfo_log_version = 5  # Changed in v61 (04-04-2019)
v0.1.61

2019-04-12 16:03 UTC, andywerner commented on octoprint_mrbeam/printing/comm_acc2.py
> +			self._power_correction_factor = _mrbeam_plugin_implementation._settings.get(['laserhead', 'correction', 'factor'])
why don't you use your method _set_power_correction_factor() here? Wouldn't it be nicer if you did?

2019-04-12 16:03 UTC, andywerner commented on octoprint_mrbeam/printing/comm_acc2.py
> -			self._intensity_factor = temp
can you please check if the following are still in use and remove them if not:
- self._feedrate_factor
- self._feedrate_dict
- self._actual_feedrate
- self._intensity_factor
- self._actual_intensity
- self._intensity_dict

2019-04-12 16:03 UTC, andywerner commented on octoprint_mrbeam/printing/comm_acc2.py
> +			new_intensity = int(round(self._actual_intensity))
Isn't this already done a few lines above?
I like your code more. But let's clean up the ole one. I might be wrong, but I still think that we don't need the self._actual_intensity any more.

2019-04-12 16:03 UTC, andywerner commented on octoprint_mrbeam/printing/comm_acc2.py
> +			self._logger.info('Intensity command changed from S{old} to S{new} (correction factor {factor})'.format(
this would be logged with every GCode command. Please don't.
If you'd like to see this for debugging, you can keep the line and either comment it out or you introduce a global contant like DEBUG, this line gets only logger if DEBUG == True but you set to False before you commit.

2019-04-12 16:03 UTC, andywerner commented on octoprint_mrbeam/printing/comm_acc2.py
> +			elif specialcmd.startswith('/terminal_show_checksums'):
please rename it to "show_checksums". we're already in the terminal...

2019-04-12 16:03 UTC, Gallore commented on octoprint_mrbeam/printing/comm_acc2.py
> +			elif specialcmd.startswith('/power_correction'):
Is it possible to set another correction factor here?
It's not. Just double checking.

2019-04-12 16:03 UTC, Gallore commented on octoprint_mrbeam/printing/comm_acc2.py
> +				self._log("   /terminal_show_checksums <x>  --> Enable: x = 1; Disable: x = 0")
also rename pls

2019-04-12 16:14 UTC, Gallore commented
One more thing, Iratxe: if we manually write a correction factor to config.yaml it would get overwritten immediately once a new value from iobeam is received, right?
Can you please introduce a key to config.yaml that is 'factor_override'. If it has a value, this value will be used as correction factor, regardless.

2019-04-16 07:30 UTC, irlaec commented on octoprint_mrbeam/__init__.py
> +		self.lh['serial'] = self._settings.get(["laserhead", "serial"])
done!

2019-04-16 07:31 UTC, irlaec commented on octoprint_mrbeam/analytics/analytics_handler.py
> +		self._deviceinfo_log_version = 5  # Changed in v61 (04-04-2019)
changed

2019-04-16 09:22 UTC, irlaec commented on octoprint_mrbeam/printing/comm_acc2.py
> +			self._power_correction_factor = _mrbeam_plugin_implementation._settings.get(['laserhead', 'correction', 'factor'])
I think that here we may not have the _mrbeam_plugin_implementation.lh initialized yet, does it make sense?

2019-04-16 09:22 UTC, irlaec commented on octoprint_mrbeam/printing/comm_acc2.py
> +			new_intensity = int(round(self._actual_intensity))
True, it's changed now

2019-04-16 09:22 UTC, irlaec commented on octoprint_mrbeam/printing/comm_acc2.py
> +			self._logger.info('Intensity command changed from S{old} to S{new} (correction factor {factor})'.format(
Deleted!

2019-04-16 09:22 UTC, irlaec commented on octoprint_mrbeam/printing/comm_acc2.py
> +			elif specialcmd.startswith('/terminal_show_checksums'):
done

2019-04-16 09:22 UTC, irlaec commented on octoprint_mrbeam/printing/comm_acc2.py
> +				self._log("   /terminal_show_checksums <x>  --> Enable: x = 1; Disable: x = 0")
done

2019-04-16 09:22 UTC, irlaec commented on octoprint_mrbeam/printing/comm_acc2.py
> -			self._intensity_factor = temp
all of them are removed now

2019-04-17 10:40 UTC, andywerner requested changes

2019-04-17 10:40 UTC, Gallore commented on octoprint_mrbeam/__init__.py
> +		self.lh['gcode_intensity_limit'] = self._settings.get(["laserhead", "correction", "gcode_intensity_limit"])
```suggestion
```

2019-04-17 10:41 UTC, andywerner approved these changes

2019-04-17 10:41 UTC, merged