F job time estimation analytics
mrbeam/MrBeamPlugin pull request #498
Opened 2019-05-29 14:03 UTC by irlaec

2019-05-31 12:35 UTC, irlaec commented
![](https://github.trello.services/images/mini-trello-icon.png) [Analytics for job time estimation](https://trello.com/c/CnyVi4Gd/129-analytics-for-job-time-estimation)

2019-06-03 13:20 UTC, andywerner approved these changes

2019-06-03 13:20 UTC, Gallore commented
please update the analytics documentation.

2019-06-03 13:21 UTC, andywerner requested changes
increase verion number, update documentation

2019-06-04 09:02 UTC, andywerner approved these changes

2019-06-04 09:03 UTC, merged