Collect more analytics
mrbeam/MrBeamPlugin pull request #547
Opened 2019-08-01 09:13 UTC by irlaec

2019-08-01 09:13 UTC, irlaec commented
![](https://github.trello.services/images/mini-trello-icon.png) [Analytics: Collect more values](https://trello.com/c/XngFZw4y/176-analytics-collect-more-values)

2019-08-01 09:13 UTC, irlaec commented
![](https://github.trello.services/images/mini-trello-icon.png) [Analytics: Collect more values](https://trello.com/c/XngFZw4y/176-analytics-collect-more-values)

2019-08-01 09:13 UTC, irlaec commented
![](https://github.trello.services/images/mini-trello-icon.png) [Analytics: Collect more values](https://trello.com/c/XngFZw4y/176-analytics-collect-more-values)

2019-08-01 09:13 UTC, irlaec commented
![](https://github.trello.services/images/mini-trello-icon.png) [Analytics: Collect more values](https://trello.com/c/XngFZw4y/176-analytics-collect-more-values)

2019-08-01 09:13 UTC, irlaec commented
![](https://github.trello.services/images/mini-trello-icon.png) [Analytics: Collect more values](https://trello.com/c/XngFZw4y/176-analytics-collect-more-values)

2019-08-01 09:13 UTC, irlaec commented
![](https://github.trello.services/images/mini-trello-icon.png) [Analytics: Collect more values](https://trello.com/c/XngFZw4y/176-analytics-collect-more-values)

2019-08-01 09:13 UTC, irlaec commented
![](https://github.trello.services/images/mini-trello-icon.png) [Analytics: Collect more values](https://trello.com/c/XngFZw4y/176-analytics-collect-more-values)

2019-08-01 09:13 UTC, irlaec commented
![](https://github.trello.services/images/mini-trello-icon.png) [Analytics: Collect more values](https://trello.com/c/XngFZw4y/176-analytics-collect-more-values)

2019-08-01 09:15 UTC, irlaec commented
![](https://github.trello.services/images/mini-trello-icon.png) [Analytics: Collect more values](https://trello.com/c/XngFZw4y/176-analytics-collect-more-values)

2019-08-02 07:59 UTC, andywerner requested changes
timestamps

2019-08-02 07:59 UTC, andywerner commented on octoprint_mrbeam/static/js/analytics.js
> +            payload['ts'] = payload['ts'] || new Date().getTime()/1000;
Do we already have frontend analytics released? if yes, you'll end up with two different ts formats in the backend... Let's talk about this one.

2019-08-02 07:59 UTC, andywerner commented on octoprint_mrbeam/static/js/wizard_general.js
> +                self.uuid(self.settings.settings.plugins.findmymrbeam.uuid());
Can you be sure, that settings are already loaded in onAllBound?

2019-08-02 07:59 UTC, andywerner commented on octoprint_mrbeam/static/js/wizard_general.js
> +                self.uuid(self.settings.settings.plugins.findmymrbeam.uuid());
I asked Gina since I'm never sure.

2019-08-02 07:59 UTC, andywerner commented on octoprint_mrbeam/static/js/wizard_general.js
> +                self.uuid(self.settings.settings.plugins.findmymrbeam.uuid());
ok, it find. data are there. http://docs.octoprint.org/en/master/plugins/viewmodels.html#web-interface-startup

2019-08-02 14:48 UTC, irlaec commented on octoprint_mrbeam/static/js/analytics.js
> +            payload['ts'] = payload['ts'] || new Date().getTime()/1000;
I left it as it was.

2019-08-07 09:46 UTC, andywerner approved these changes

2019-08-07 09:46 UTC, Gallore commented on octoprint_mrbeam/static/js/convert.js
> +                console.log('#######################');
```suggestion
```

2019-08-07 09:46 UTC, Gallore commented on octoprint_mrbeam/static/js/convert.js
> +                    console.log(currentDesign);
pls remove log lines

2019-08-07 10:35 UTC, irlaec commented on octoprint_mrbeam/static/js/convert.js
> +                    console.log(currentDesign);
removed

2019-08-07 10:36 UTC, irlaec commented on octoprint_mrbeam/static/js/convert.js
> +                console.log('#######################');
removed

2019-08-08 09:06 UTC, andywerner requested changes

2019-08-08 09:06 UTC, Gallore commented on octoprint_mrbeam/static/js/convert.js
> +                    console.log(clip_working_area)
```suggestion
```

2019-08-08 09:24 UTC, merged