Customer reviews
mrbeam/MrBeamPlugin pull request #594
Opened 2019-10-01 15:37 UTC by irlaec

2019-10-01 16:28 UTC, Gallore commented
I know I said you should use the laser safety screen as a template… But now I found that there is an easier way to read user settings on the frontend from the LoginStateViewModel: (here accessed via workinAreaViewModel:)
`mrbeam.viewModels.workingAreaViewModel.loginState.currentUser()`

I’d like to discuss with you tomorrow if it makes sense to refactor your code for the reviews so that it takes advantage of this.
One potential pitfall of this above is that I don’t know when/if it updates during runtime.

2019-10-01 16:35 UTC, Gallore commented
Theres also the userSettingsViewModel:
https://docs.octoprint.org/en/master/plugins/viewmodels.html#dependencies

2019-10-02 10:47 UTC, Gallore commented
`mrbeam.viewModels.userSettingsViewModel.updateSettings(mrbeam.viewModels.workingAreaViewModel.loginState.currentUser().name, {mrbeam:{andytest:'hallo'}})`

this one wipes all mrbeam suer settings. So a logged in suer can add any settings he wants.

2019-10-08 15:01 UTC, andywerner requested changes

2019-10-08 15:01 UTC, andywerner commented on octoprint_mrbeam/__init__.py
> +			num_succ_jobs = 0,
move to usage,yaml

2019-10-08 15:01 UTC, andywerner commented on octoprint_mrbeam/__init__.py
> +		return self._current_user
not needed any more

2019-10-08 15:01 UTC, andywerner commented on octoprint_mrbeam/static/js/review.js
> +                console.log('############ NOW YES: '+self.justGaveReview());
remove

2019-10-08 15:10 UTC, irlaec commented on octoprint_mrbeam/__init__.py
> +		return self._current_user
I actually need it...

2019-10-08 15:10 UTC, irlaec commented on octoprint_mrbeam/__init__.py
> +			num_succ_jobs = 0,
moved

2019-10-08 15:11 UTC, irlaec commented on octoprint_mrbeam/static/js/review.js
> +                console.log('############ NOW YES: '+self.justGaveReview());
removed

2019-10-09 08:48 UTC, merged