Add new detection algorthim
mrbeam/MrBeamPlugin pull request #684
Opened 2020-01-02 09:58 UTC by amrsoll

- Single frame detection
- Auto adjust shutter speed to detect reference markers instead of the center of the frame

2020-01-10 15:55 UTC, amrsoll commented
Still need to do before being semi-stable :

- Handle errors better (especially when start/stopping, opening lid etc...)
- get signal from front-end to know if it's ready to receive a refreshed picture
- Analytics : compare the results of the 2 algorithms
- Scale distortion matrix to accommodate higher resolution pictures
- Detect movement in order not to serve the same image twice

2020-01-15 19:25 UTC, andywerner requested changes
we spoke about the todos

Marker detection ToDos:
- remember last know position of a marker (blocker for beta)
- slider: local maxima - check if it’s really a marker
- detected blobs: cycle is this a marker?
- reduce file size of the first image
- redo logic when markers flash on frontend
- Difference in file size between grey and colored.
- Timer to resend even with very slow connection
- use brightness for shutterspeed
- apply_best_shutter_speed() (maybe)

2020-01-20 11:49 UTC, amrsoll commented
- [x] remember last know position of a marker (blocker for beta)
- [ ] slider local maxima - check if it’s really a marker
- [ ] detected blobs: cycle is this a marker?
- [x] reduce file size of the first image
- [ ] redo logic when markers flash on frontend
- [ ] Difference in file size between grey and colored.
- [ ] Timer to resend even with very slow connection
- [ ] use brightness for shutterspeed
- [ ] apply_best_shutter_speed() (maybe)

2020-01-21 15:31 UTC, andywerner approved these changes

2020-01-21 15:32 UTC, merged