Remove legacy marker detection
mrbeam/MrBeamPlugin pull request #793
Opened 2020-03-25 21:58 UTC by amrsoll

Also makes less debug logging

2020-03-26 10:28 UTC, amrsoll commented
Closing while waiting for other commits

2020-03-30 13:58 UTC, andywerner requested changes

2020-03-30 13:58 UTC, Gallore commented on octoprint_mrbeam/iobeam/lid_handler.py
> -		if self._photo_creator is not None and self.camEnabled:
pl also remove camEnabled from settings

2020-03-31 10:07 UTC, andywerner approved these changes

2020-04-01 00:17 UTC, merged