v0.6.5
mrbeam/MrBeamPlugin pull request #797
Opened 2020-04-03 05:59 UTC by irlaec

2020-04-03 07:03 UTC, amrsoll commented on octoprint_mrbeam/static/js/working_area.js
> +
Is quickscan ready for Beta @Gallore ?

2020-04-03 07:16 UTC, amrsoll commented
- Removes the dependency on the legacy algorithm (and a bg associated with it)
- Adds some better install process for the desktop

2020-04-03 07:47 UTC, Gallore commented on octoprint_mrbeam/static/js/working_area.js
> +
nope!

2020-04-03 07:56 UTC, andywerner requested changes
Quick scan must be hidden! It's not in a beta state.

2020-04-05 15:50 UTC, amrsoll approved these changes
Everything is fixed now :)

2020-04-06 14:11 UTC, andywerner approved these changes

2020-04-07 06:07 UTC, merged