MMAL Error : Attempt to fix & Notify Front End it case it doesn't
mrbeam/MrBeamPlugin pull request #812
Opened 2020-04-15 23:59 UTC by amrsoll

Attempt to completely avoid starting a PhotoCreator thread while an other one is using the camera (current belief behind the cause of the MMAL Error

This message shows in case the error happens
![Screenshot from 2020-04-16 01-48-11](https://user-images.githubusercontent.com/24782867/79400002-308ac480-7f85-11ea-9552-59c2d272bb71.png)

These are the threading.Event elements that makes it possible :

- `active` flag : whether the camera is in use
- `stopEvent` : whether we are trying to exit the current PhotoCreator thread

2020-04-16 15:40 UTC, amrsoll commented
New error message displayed after 2 camera restarts : 
![Screenshot from 2020-04-16 17-32-12](https://user-images.githubusercontent.com/24782867/79476509-5a85ca80-8009-11ea-9712-fee8e5bc2a80.png)

2020-04-16 16:41 UTC, andywerner requested changes

2020-04-16 16:41 UTC, Gallore commented on octoprint_mrbeam/static/js/user_notification_viewmodel.js
> +                    url: 'https://support.mr-beam.org/en/support/solutions/articles/43000570474-error-camera-error',
```suggestion
                    url: 'https://support.mr-beam.org/support/solutions/articles/43000570474-error-camera-error',
```

2020-04-17 23:27 UTC, amrsoll commented
TODO : Add analytics : Are we able to recover from this error?

2020-04-21 14:43 UTC, andywerner approved these changes

2020-04-21 14:43 UTC, merged