Progressive cut: work with custom materials, explained and visible
mrbeam/MrBeamPlugin pull request #881
Opened 2020-07-10 07:26 UTC by irlaec

![Screenshot from 2020-07-10 09-25-21](https://user-images.githubusercontent.com/28774305/87128179-7955cf00-c28f-11ea-982c-cbed52f71d87.png)

2020-07-10 08:19 UTC, irlaec commented
![](https://github.trello.services/images/mini-trello-icon.png) [Progressive Cut integration](https://trello.com/c/O6GoEnFM/438-progressive-cut-integration)

2020-07-13 14:44 UTC, andywerner requested changes

2020-07-13 14:44 UTC, Gallore commented on octoprint_mrbeam/static/js/convert.js
> +				console.log('################## P WHATEVER THIS IS')
I assume this should be removed.

2020-07-14 08:24 UTC, irlaec commented on octoprint_mrbeam/static/js/convert.js
> +				console.log('################## P WHATEVER THIS IS')
removed

2020-07-14 08:24 UTC, merged