Restrict calibration tool to when the mode is ON.
mrbeam/MrBeamPlugin pull request #907
Opened 2020-08-04 09:43 UTC by amrsoll

2020-08-06 09:19 UTC, andywerner requested changes
pls add SUPPORT MODE to calibration tool mode

2020-08-06 09:19 UTC, Gallore commented on octoprint_mrbeam/__init__.py
> +		ret = set_support_mode(self)
pls rename to 'check_support_mode'

2020-08-06 09:19 UTC, Gallore commented on octoprint_mrbeam/__init__.py
> +			return NO_CONTENT
pls return FORBIDDEN

2020-08-06 15:03 UTC, amrsoll commented
I'm adding support mode in the usb key recipee

2020-08-07 08:47 UTC, andywerner approved these changes

2020-08-07 08:48 UTC, merged